function calculator
% Denis
% Mar 23rd, 2019
% https://github.com/Oslomayor/MATLAB-Calcultor
clear all
global GUI
global cache
global cache_in
global cache_out
GUI.fh = figure(...
    'units','pixels',...
    'numbertitle','off',...
    'name','我为何这么帅',...
    'menubar','none',...
    'WindowButtonMotionFcn',@func_refresh,...
    'position',[500 300 360 460]);
GUI.Button_0 = uicontrol(...
    'Parent',GUI.fh,...
    'position',[10 10 130 50],...
    'String','0',...
    'fontsize',18,...
    'callback',@func_0);
GUI.Button_point = uicontrol(...
    'Parent',GUI.fh,...
    'position',[150 10 60 50],...
    'String','.',...
    'fontsize',18,...
    'callback',@func_point);
GUI.Button_1 = uicontrol(...
    'Parent',GUI.fh,...
    'Position',[10 70 60 50],...
    'String','1',...
    'fontsize',18,...
    'callback',@func_1);
GUI.Button_2 = uicontrol(...
    'Parent',GUI.fh,...
    'Position',[80 70 60 50],...
    'String','2',...
    'fontsize',18,...
    'callback',@func_2);
GUI.Button_3 = uicontrol(...
    'Parent',GUI.fh,...
    'Position',[150 70 60 50],...
    'String','3',...
    'fontsize',18,...
    'callback',@func_3);
GUI.Button_4 = uicontrol(...
    'Parent',GUI.fh,...
    'Position',[10 130 60 50],...
    'String','4',...
    'fontsize',18,...
    'callback',@func_4);
GUI.Button_5 = uicontrol(...
    'Parent',GUI.fh,...
    'Position',[80 130 60 50],...
    'String','5',...
    'fontsize',18,...
    'callback',@func_5);
GUI.Button_6 = uicontrol(...
    'Parent',GUI.fh,...
    'Position',[150 130 60 50],...
    'String','6',...
    'fontsize',18,...
    'callback',@func_6);
GUI.Button_7 = uicontrol(...
    'Parent',GUI.fh,...
    'Position',[10 190 60 50],...
    'String','7',...
    'fontsize',18,...
    'callback',@func_7);
GUI.Button_8 = uicontrol(...
    'Parent',GUI.fh,...
    'Position',[80 190 60 50],...
    'String','8',...
    'fontsize',18,...
    'callback',@func_8);
GUI.Button_9 = uicontrol(...
    'Parent',GUI.fh,...
    'Position',[150 190 60 50],...
    'String','9',...
    'fontsize',18,...
    'callback',@func_9);
GUI.Button_plus = uicontrol(...
    'Parent',GUI.fh,...
    'position',[220 10 60 50],...
    'String','+',...
    'fontsize',18,...
    'callback',@func_plus);
GUI.Button_minus = uicontrol(...
    'Parent',GUI.fh,...
    'position',[220 70 60 50],...
    'String','-',...
    'fontsize',18,...
    'callback',@func_minus);
GUI.Button_multiply = uicontrol(...
    'Parent',GUI.fh,...
    'position',[220 130 60 50],...
    'String','*',...
    'fontsize',18,...
    'callback',@func_multiply);
GUI.Button_devide = uicontrol(...
    'Parent',GUI.fh,...
    'position',[220 190 60 50],...
    'String','/',...
    'fontsize',18,...
    'callback',@func_devide);
GUI.Button_answer = uicontrol(...
    'Parent',GUI.fh,...
    'position',[290 10 60 110],...
    'String','=',...
    'fontsize',18,...
    'callback',@func_answer);
GUI.Button_reciprocal = uicontrol(...
    'Parent',GUI.fh,...
    'position',[290 130 60 50],...
    'String','1/x',...
    'fontsize',18,...
    'callback',@func_reciprocal);
GUI.Button_percent = uicontrol(...
    'Parent',GUI.fh,...
    'position',[290 190 60 50],...
    'String','%',...
    'fontsize',18,...
    'callback',@func_percent);
GUI.Button_back = uicontrol(...
    'Parent',GUI.fh,...
    'Position',[10 250 60 50],...
    'String','←',...
    'fontsize',18,...
    'callback',@func_back);
GUI.Button_CE = uicontrol(...
    'Parent',GUI.fh,...
    'Position',[80 250 60 50],...
    'String','CE',...
    'fontsize',18,...
    'callback',@func_clearend);
GUI.Button_C = uicontrol(...
    'Parent',GUI.fh,...
    'Position',[150 250 60 50],...
    'String','C',...
    'fontsize',18,...
    'callback',@func_clear);
GUI.Button_plusminus = uicontrol(...
    'Parent',GUI.fh,...
    'Position',[220 250 60 50],...
    'String','±',...
    'fontsize',18,...
     'callback',@func_plusminus);
GUI.Button_root = uicontrol(...
    'Parent',GUI.fh,...
    'Position',[290 250 60 50],...
    'String','√',...
    'fontsize',18,...
     'callback',@func_root);
GUI.Text = uicontrol(...
    'Parent',GUI.fh,...
    'Style','text',...
    'BackgroundColor','white',...
    'Position',[10 310 340 100],...
    'hor','right',...
    'String','',...
    'fontsize',28);
function func_0(~,~)
cache_in = [cache_in,'0'];
end
function func_1(~,~)
cache_in = [cache_in,'1'];
end
function func_2(~,~)
cache_in = [cache_in,'2'];
end
function func_3(~,~)
cache_in = [cache_in,'3'];
end
function func_4(~,~)
cache_in = [cache_in,'4'];
end
function func_5(~,~)
cache_in = [cache_in,'5'];
end
function func_6(~,~)
cache_in = [cache_in,'6'];
end
function func_7(~,~)
cache_in = [cache_in,'7'];
end
function func_8(~,~)
cache_in = [cache_in,'8'];
end
function func_9(~,~)
cache_in = [cache_in,'9'];
end
function func_point(~,~)
cache_in = [cache_in,'.'];
end
function func_plus(~,~)
cache_in = [cache_in,'+'];
end
function func_minus(~,~)
cache_in = [cache_in,'-'];
end
function func_multiply(~,~)
cache_in = [cache_in,'*'];
end
function func_devide(~,~)
cache_in = [cache_in,'/'];
end
function func_answer(~,~)
cache_out = eval(cache_in);
cache = {cache_in;cache_out};
set(GUI.Text,'String',cache);
end
function func_refresh(~,~)
cache = {cache_in;cache_out};
set(GUI.Text,'String',cache);
end
function func_clear(~,~)
cache_in = [];
cache_out = [];
cache = [];
end
function func_clearend(~,~)
pat = '[-+*/][0-9]+';
res = regexp(cache_in,pat,'match');
%% res = {'*65', '-69', '/963', '+6889'}
res = res(end);
%% res = {'+6889'}
res = res{1};
%% res = '+6889'
%%
len = size(res);
len = len(2);
cache_in = cache_in(1:end-len+1);
end
function func_back(~,~)
cache_in = cache_in(1:end-1);
end
function func_reciprocal(~,~)
cache_in = [cache_in,'^(-1)'];
end
function func_percent(~,~)
pat = '[-+*/][0-9]+';
res = regexp(cache_in,pat,'match');
res = res(end);
res = res{1};
len = size(res);
len = len(2);
lastnum = cache_in(end-len+2:end);
class(lastnum);
fraction = num2str(str2num(lastnum)/100);
cache_in = [cache_in(1:end-len+1),fraction];
end
function func_plusminus(~,~)
cache_in = [cache_in,'*(-1)'];
end
function func_root(~,~)
cache_in = [cache_in,'^(0.5)'];
end
end
